// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UseCase.Data;

#nullable disable

namespace UseCase.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20241219110254_datainserted")]
    partial class datainserted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UseCase.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserID = 1,
                            desc = "Dev"
                        },
                        new
                        {
                            Id = 2,
                            UserID = 2,
                            desc = "Testing"
                        },
                        new
                        {
                            Id = 3,
                            UserID = 3,
                            desc = "Analyst"
                        },
                        new
                        {
                            Id = 4,
                            UserID = 4,
                            desc = "HR"
                        },
                        new
                        {
                            Id = 5,
                            UserID = 6,
                            desc = "Requisition"
                        });
                });

            modelBuilder.Entity("UseCase.Data.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Aman"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Anthony"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Akash"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Aanand"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Akansha"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Aastha"
                        });
                });

            modelBuilder.Entity("UseCase.Data.Role", b =>
                {
                    b.HasOne("UseCase.Data.User", "User")
                        .WithMany("Role")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UseCase.Data.User", b =>
                {
                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
